import type { Metadata } from "next";
import { Literata } from "next/font/google";
import "./globals.css";

// Sidebar
import Sidebar from "./components/sidebar";

const literata = Literata({
  variable: "--font-literata",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "ekoubuyoi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${literata.variable} ${literata.className} h-full antialiased`}
    >
      <body className="min-h-full md:py-20 md:px-96 gap-5 flex flex-row">
        <Sidebar />
        <main className="font-literata flex-1 h-[80vh] overflow-y-auto bg-[#F9F7F2] shadow-[8px_8px_0px_0px_#282828] border-3 rounded-sm p-4">{children}</main>
      </body>
    </html>
  );
}
